# -*- coding: utf-8 -*-
"""개화파와 위정척사파 분류기.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d77zl8FQXiCzrV8d_POfAit0-9N8CHfu
"""

pip install requests beautifulsoup4 google-generativeai

import requests
from bs4 import BeautifulSoup
import google.generativeai as genai
import sys
import streamlit as st  # 이 줄이 없으면 맨 위에 추가해주세요!

# 이제 실제 키 대신 '비밀 금고'를 참조합니다
GOOGLE_API_KEY = st.secrets["GEMINI_API_KEY"]
genai.configure(api_key=GOOGLE_API_KEY)

# 모델 설정 (가볍고 빠른 gemini-1.5-flash 사용 권장)
model = genai.GenerativeModel('gemini-2.5-flash')

# ---------------------------------------------------------
# 2. 웹 스크래핑 모듈 (국사편찬위원회 데이터베이스)
# ---------------------------------------------------------
def scrape_history_data(name):
    """
    국사편찬위원회 한국사데이터베이스 통합검색에서 인물 관련 텍스트를 수집합니다.
    """
    print(f"🔍 국사편찬위원회 DB에서 '{name}' 관련 사료를 검색 중입니다...")

    # 국사편찬위원회 통합검색 URL
    # 실제 데이터 구조에 따라 URL이나 파라미터는 달라질 수 있습니다.
    base_url = "http://db.history.go.kr/integrated/search/searchResult.do"
    params = {
        'keyword': name,
        'itemIds': '300', # 인물/시대 관련 카테고리 (필요시 조정)
    }

    try:
        # 타임아웃 설정 (서버 응답 지연 대비)
        response = requests.get(base_url, params=params, timeout=10)
        response.raise_for_status()

        soup = BeautifulSoup(response.text, 'html.parser')

        # 검색 결과 텍스트 추출
        # (사이트 구조 변경에 유연하게 대응하기 위해 검색 결과 리스트의 텍스트를 가져옵니다)
        results = []

        # 검색 결과 리스트 영역 (dl, li 등 일반적인 목록 태그 탐색)
        contents = soup.select('.search_result li dl dd')

        if not contents:
            # 다른 구조일 경우를 대비한 예비 선택자
            contents = soup.select('.ul_list li')

        for content in contents[:4]: # 토큰 절약을 위해 상위 4개 결과만 사용
            text = content.get_text(strip=True)
            if len(text) > 30: # 너무 짧은 노이즈 데이터 제외
                results.append(text)

        if not results:
            return None

        # 리스트를 하나의 문자열로 합침
        return " ".join(results)

    except Exception as e:
        print(f"⚠️ 스크래핑 중 오류 발생: {e}")
        return None

# ---------------------------------------------------------
# 3. 분류 모델 모듈 (Gemini API 활용)
# ---------------------------------------------------------
def classify_figure(name, context_text):
    """
    수집된 텍스트를 바탕으로 Gemini 모델을 통해 개화파/위정척사파를 분류합니다.
    """
    if not context_text:
        return "정보 부족으로 판단 불가"

    print("🤖 Gemini가 데이터를 분석하고 있습니다...")

    # 프롬프트 구성
    prompt = f"""
    당신은 한국 근대사 역사학자입니다.
    아래 제공된 '국사편찬위원회 검색 결과(텍스트)'를 바탕으로, '{name}'이라는 인물의 정치/사상적 성향을 분석해주세요.

    [분류 기준]
    1. **개화파 (Enlightenment Party)**: 문호 개방, 근대화 추진, 서양/일본 문물 수용 주장.
    2. **위정척사파 (Orthodoxy Party)**: 성리학적 질서 수호, 통상 반대, 외세 배격 주장.
    3. **기타/중립**: 위 두 파벌에 명확히 속하지 않거나 판단하기 어려운 경우.

    [제공된 텍스트]
    {context_text[:2000]}

    [응답 형식]
    반드시 아래 형식을 지켜주세요:
    - **분류**: [개화파 / 위정척사파 / 기타 중 택1]
    - **신뢰도**: [상 / 중 / 하]
    - **핵심 근거**: [텍스트에 기반한 1~2문장 요약]
    """

    try:
        # Gemini 모델 호출
        response = model.generate_content(prompt)
        return response.text

    except Exception as e:
        return f"⚠️ API 호출 중 오류 발생: {e}"

# ---------------------------------------------------------
# 4. 메인 실행 함수
# ---------------------------------------------------------
def main():
    print("\n" + "="*50)
    print("   🏛️  역사 인물 성향 분류기 (Powered by Google Gemini)   ")
    print("="*50)

    while True:
        target_name = input("\n📝 분류할 인물 이름을 입력하세요 ('q' 입력 시 종료): ").strip()

        if target_name.lower() == 'q':
            print("프로그램을 종료합니다.")
            break

        if not target_name:
            continue

        # 1. 데이터 수집 (Scraping)
        history_context = scrape_history_data(target_name)

        # 2. 모델 분류 (Inference)
        if history_context:
            result = classify_figure(target_name, history_context)
            print("\n" + "-"*50)
            print(f"📊 [분석 결과] : {target_name}")
            print("-" * 50)
            print(result)
            print("-" * 50)
        else:
            print(f"❌ '{target_name}'에 대한 유의미한 사료를 찾지 못했습니다. (검색어 확인 필요)")

if __name__ == "__main__":
    main()

import requests
from bs4 import BeautifulSoup
import google.generativeai as genai
import sys
import time

# ---------------------------------------------------------
# 1. 설정 및 초기화
# ---------------------------------------------------------
# 이제 실제 키 대신 '비밀 금고'를 참조합니다
GOOGLE_API_KEY = st.secrets["GEMINI_API_KEY"]
genai.configure(api_key=GOOGLE_API_KEY)

try:
    genai.configure(api_key=GOOGLE_API_KEY)
    # 1.5-flash 모델 사용 (속도가 빠름)
    model = genai.GenerativeModel('gemini-1.5-flash')
except Exception as e:
    print(f"⚠️ API 설정 오류: {e}")
    print("API 키가 올바른지 확인해주세요.")
    sys.exit()

# ---------------------------------------------------------
# 2. 웹 스크래핑 모듈 (헤더 추가로 차단 우회)
# ---------------------------------------------------------
def scrape_history_data(name):
    """
    국사편찬위원회 통합검색에서 인물 관련 텍스트를 수집합니다.
    User-Agent를 추가하여 400 에러를 방지합니다.
    """
    print(f"🔍 국사편찬위원회 DB에서 '{name}' 관련 사료를 검색 중입니다...")

    # 통합검색 URL
    base_url = "http://db.history.go.kr/integrated/search/searchResult.do"

    # [중요] 브라우저인 척 위장하기 위한 헤더 설정
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36',
        'Referer': 'http://db.history.go.kr/',
        'Accept-Language': 'ko-KR,ko;q=0.9,en-US;q=0.8,en;q=0.7'
    }

    params = {
        'keyword': name,
        'itemIds': '300', # 인물 관련 (오류 발생 시 이 줄을 주석 처리해보세요)
    }

    try:
        # headers 옵션 추가
        response = requests.get(base_url, params=params, headers=headers, timeout=10)
        response.raise_for_status() # 400/500 에러 발생 시 예외 처리

        soup = BeautifulSoup(response.text, 'html.parser')

        results = []

        # 사이트 구조에 맞춰 텍스트 추출 (구조가 유동적이므로 여러 선택자 시도)
        # 1. 검색 결과 리스트 요약 내용
        contents = soup.select('.search_result li dl dd')

        # 2. 만약 위 선택자로 못 찾으면 다른 클래스 시도
        if not contents:
            contents = soup.select('.cont_list li .txt')

        for content in contents[:5]:
            text = content.get_text(strip=True)
            if len(text) > 20:
                results.append(text)

        if not results:
            print(f"   ℹ️ 검색 결과 텍스트를 찾지 못했습니다. (페이지 구조가 다를 수 있음)")
            return None

        return " ".join(results)

    except requests.exceptions.HTTPError as e:
        print(f"⚠️ HTTP 오류 발생 (400/500): {e}")
        print("   -> 서버가 요청을 거부했습니다. 잠시 후 다시 시도하거나 헤더를 확인하세요.")
        return None
    except Exception as e:
        print(f"⚠️ 기타 스크래핑 오류: {e}")
        return None

# ---------------------------------------------------------
# 3. 분류 모델 모듈
# ---------------------------------------------------------
def classify_figure(name, context_text):
    if not context_text:
        return "정보 부족으로 판단 불가"

    print("🤖 Gemini가 데이터를 분석하고 있습니다...")

    prompt = f"""
    당신은 한국사 전문가입니다.
    아래 제공된 텍스트는 국사편찬위원회에서 '{name}'으로 검색된 결과입니다.
    이 내용을 바탕으로 이 인물이 '개화파'인지 '위정척사파'인지 분류해주세요.

    [제공된 텍스트]
    {context_text[:2000]}

    [응답 형식]
    - **분류**: [개화파 / 위정척사파 / 기타]
    - **이유**: [텍스트에 기반한 1문장 요약]
    """

    try:
        response = model.generate_content(prompt)
        return response.text
    except Exception as e:
        return f"⚠️ API 호출 중 오류 발생: {e}"

# ---------------------------------------------------------
# 4. 메인 실행
# ---------------------------------------------------------
def main():
    print("\n" + "="*50)
    print("   🏛️  역사 인물 성향 분류기 (수정버전)   ")
    print("="*50)

    while True:
        target_name = input("\n📝 인물 이름 입력 ('q' 종료): ").strip()

        if target_name.lower() == 'q':
            print("종료합니다.")
            break

        if not target_name:
            continue

        # 1. 수집
        history_context = scrape_history_data(target_name)

        # 2. 분석
        if history_context:
            result = classify_figure(target_name, history_context)
            print("\n" + "-"*50)
            print(f"📊 결과: {target_name}")
            print(result)
            print("-" * 50)
        else:
            print(f"❌ '{target_name}' 데이터를 가져오지 못해 분석할 수 없습니다.")

if __name__ == "__main__":
    main()

import requests
from bs4 import BeautifulSoup
import google.generativeai as genai
import sys
import warnings

# ---------------------------------------------------------
# 1. 설정 및 초기화
# ---------------------------------------------------------
# 경고 메시지(FutureWarning) 숨기기 (깔끔한 출력을 위해)
warnings.filterwarnings("ignore")

# Google AI Studio API KEY 입력
GOOGLE_API_KEY = "AIzaSyBEmAHr7r1i2mt8yu6qjp3P79ErIfQrIfw"

try:
    genai.configure(api_key=GOOGLE_API_KEY)
    model = genai.GenerativeModel('gemini-2.5-flash')
except Exception as e:
    print(f"⚠️ API 설정 오류: {e}")
    sys.exit()

# ---------------------------------------------------------
# 2. 웹 스크래핑 모듈 (최신 URL 적용)
# ---------------------------------------------------------
def scrape_history_data(name):
    """
    국사편찬위원회 한국사데이터베이스에서 인물 데이터를 수집합니다.
    (최신 HTTPS 주소 및 파라미터 적용)
    """
    print(f"🔍 국사편찬위원회 DB에서 '{name}' 검색 중...")

    # [수정됨] 최신 검색 URL (HTTPS 적용)
    base_url = "https://db.history.go.kr/search/searchResult.do"

    # [수정됨] 브라우저 위장 헤더
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
        'Referer': 'https://db.history.go.kr/',
        'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8'
    }

    # [수정됨] 파라미터 이름 변경 (keyword -> searchKeyword)
    params = {
        'searchKeyword': name,
        'sort': 'levelId',  # 정확도/중요도 순 정렬 유도
        'limit': '20'
    }

    try:
        # verify=False는 SSL 인증서 오류 방지 (필요 시 사용)
        response = requests.get(base_url, params=params, headers=headers, timeout=10)

        # 404, 500 등 에러 체크
        if response.status_code == 404:
            print("❌ 오류: 페이지를 찾을 수 없습니다 (URL 변경됨).")
            return None
        response.raise_for_status()

        soup = BeautifulSoup(response.text, 'html.parser')

        results = []

        # [수정됨] 실제 사이트 구조에 맞는 선택자 (검색 결과 리스트)
        # 1. <ul> 리스트 안의 <li> 텍스트 추출 시도
        list_items = soup.select('.search_list li .cont')

        # 2. 만약 구조가 다르면 다른 클래스 시도
        if not list_items:
            list_items = soup.select('.result_list li')

        for item in list_items[:3]: # 상위 3개만 추출
            text = item.get_text(strip=True)
            if len(text) > 30: # 너무 짧은 제목 등은 제외
                results.append(text)

        # 결과가 없을 경우
        if not results:
            # 인물이 검색되지 않았거나 결과 텍스트를 못 찾은 경우
            print("   ℹ️ 검색 결과에서 텍스트를 추출하지 못했습니다.")
            return None

        return " ".join(results)

    except requests.exceptions.HTTPError as e:
        print(f"⚠️ HTTP 오류 ({response.status_code}): {e}")
        return None
    except Exception as e:
        print(f"⚠️ 스크래핑 중 알 수 없는 오류: {e}")
        return None

# ---------------------------------------------------------
# 3. 분류 모델 모듈
# ---------------------------------------------------------
def classify_figure(name, context_text):
    if not context_text:
        return "데이터 부족으로 분석 불가"

    print("🤖 Gemini가 사료를 분석하고 있습니다...")

    prompt = f"""
    당신은 한국사 전문가입니다.
    아래 국사편찬위원회 검색 결과(텍스트)를 바탕으로 '{name}'의 성향을 분석하세요.

    [분석 요청]
    이 인물이 '개화파(Enlightenment)'인지 '위정척사파(Orthodoxy)'인지 분류해주세요.

    [텍스트]
    {context_text[:2500]}

    [출력 형식]
    - **분류**: [개화파 / 위정척사파 / 중립 또는 기타]
    - **핵심 근거**: [텍스트 내용을 바탕으로 한 문장 요약]
    """

    try:
        response = model.generate_content(prompt)
        return response.text
    except Exception as e:
        return f"⚠️ 분석 중 오류: {e}"

# ---------------------------------------------------------
# 4. 메인 실행
# ---------------------------------------------------------
def main():
    print("\n" + "="*50)
    print("   🏛️  역사 인물 성향 분류기 (v2.0 Fix)   ")
    print("="*50)

    while True:
        target_name = input("\n📝 인물 이름 입력 ('q' 종료): ").strip()

        if target_name.lower() == 'q':
            print("종료합니다.")
            break

        if not target_name:
            continue

        # 1. 수집
        history_context = scrape_history_data(target_name)

        # 2. 분석
        if history_context:
            result = classify_figure(target_name, history_context)
            print("\n" + "-"*50)
            print(f"📊 결과: {target_name}")
            print(result)
            print("-" * 50)
        else:
            print(f"❌ '{target_name}'에 대한 데이터를 가져올 수 없습니다.")

if __name__ == "__main__":
    main()

import requests
from bs4 import BeautifulSoup
import google.generativeai as genai
import sys
import warnings

# ---------------------------------------------------------
# 1. 설정 및 초기화
# ---------------------------------------------------------
warnings.filterwarnings("ignore") # 불필요한 경고 숨기기

# 구글 AI 스튜디오 API 키 입력
GOOGLE_API_KEY = "AIzaSyBEmAHr7r1i2mt8yu6qjp3P79ErIfQrIfw"

try:
    genai.configure(api_key=GOOGLE_API_KEY)
    model = genai.GenerativeModel('gemini-2.5-flash')
except Exception as e:
    print(f"⚠️ API 설정 오류: {e}")
    sys.exit()

# ---------------------------------------------------------
# 2. 웹 스크래핑 모듈 (1차 시도)
# ---------------------------------------------------------
def scrape_history_data(name):
    """
    국사편찬위원회 DB 크롤링을 시도합니다.
    성공하면 텍스트를 반환하고, 실패하면 None을 반환합니다.
    """
    print(f"   🔍 1단계: 국사편찬위원회 DB에서 '{name}' 검색 시도...")

    base_url = "https://db.history.go.kr/search/searchResult.do"
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/120.0.0.0 Safari/537.36',
        'Referer': 'https://db.history.go.kr/'
    }
    params = {'searchKeyword': name, 'limit': '20'}

    try:
        response = requests.get(base_url, params=params, headers=headers, timeout=5)

        if response.status_code != 200:
            return None # 404나 500 에러 시 실패 처리

        soup = BeautifulSoup(response.text, 'html.parser')
        results = []

        # 사이트 구조에 맞는 선택자 시도
        list_items = soup.select('.search_list li .cont')
        if not list_items:
            list_items = soup.select('.result_list li')

        for item in list_items[:3]:
            text = item.get_text(strip=True)
            if len(text) > 30:
                results.append(text)

        if not results:
            return None # 검색 결과 없음

        return " ".join(results)

    except Exception:
        return None # 연결 시간 초과 등 모든 에러 시 실패 처리

# ---------------------------------------------------------
# 3. 분류 모델 모듈 (Gemini)
# ---------------------------------------------------------
def classify_figure(name, context_text=None):
    """
    Gemini를 사용하여 인물을 분류합니다.
    context_text가 있으면 그것을 근거로(RAG), 없으면 Gemini 지식으로(Fallback) 분석합니다.
    """

    if context_text:
        # [Mode A] 스크래핑 성공: 제공된 텍스트 기반 분석
        print("   🤖 2단계: 수집된 사료를 바탕으로 분석 중...")
        prompt = f"""
        당신은 역사학자입니다. 아래 [제공된 사료]를 바탕으로 인물 '{name}'을 분석하세요.

        [제공된 사료]
        {context_text[:2000]}

        반드시 '개화파' 또는 '위정척사파' 중 하나로 분류하고, 사료에 나타난 근거를 제시하세요.
        """
    else:
        # [Mode B] 스크래핑 실패: Gemini 자체 지식 기반 분석 (우회)
        print("   🚀 2단계(우회): 웹 데이터 수집 실패. Gemini의 자체 지식으로 분석합니다...")
        prompt = f"""
        당신은 한국 근대사 전문가입니다. 인물 '{name}'에 대해 알고 있는 지식을 동원하여 성향을 분석하세요.

        [분석 요청]
        1. 이 인물이 **'개화파(Enlightenment Party)'**인지 **'위정척사파(Orthodoxy Party)'**인지 명확히 분류하세요.
        2. 만약 두 파벌에 속하지 않거나 독립운동가라면 '기타/중립'으로 분류하세요.
        3. 판단의 근거가 되는 주요 역사적 사건을 언급하세요.
        """

    # 공통 출력 형식 요청
    prompt += """

    [출력 형식]
    - **분류**: [개화파 / 위정척사파 / 기타]
    - **분석 모드**: [사료 기반 분석 / AI 지식 기반 분석]
    - **핵심 근거**: [한 문장 요약]
    """

    try:
        response = model.generate_content(prompt)
        return response.text
    except Exception as e:
        return f"⚠️ API 호출 오류: {e}"

# ---------------------------------------------------------
# 4. 메인 실행
# ---------------------------------------------------------
def main():
    print("\n" + "="*60)
    print("   🏛️  역사 인물 성향 분류기 (하이브리드 버전)   ")
    print("      (웹 데이터가 없으면 AI 지식으로 자동 전환됨)")
    print("="*60)

    while True:
        target_name = input("\n📝 인물 이름 입력 ('q' 종료): ").strip()

        if target_name.lower() == 'q':
            print("프로그램을 종료합니다.")
            break

        if not target_name:
            continue

        print("-" * 60)

        # 1. 스크래핑 시도
        history_context = scrape_history_data(target_name)

        if not history_context:
            print(f"   ⚠️ 알림: 국사편찬위원회에서 '{target_name}' 데이터를 찾지 못하거나 접근이 차단되었습니다.")

        # 2. 분류 (컨텍스트 유무에 따라 내부 로직이 달라짐)
        result = classify_figure(target_name, history_context)

        print("-" * 60)
        print(f"📊 [결과 리포트]: {target_name}")
        print(result)
        print("=" * 60)

if __name__ == "__main__":
    main()
