# -*- coding: utf-8 -*-
"""고려 말 온건파 사대부와 급진파 사대부의 분류모델.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IrN7kK4MMENusyJk-ASgnHO5qNfPr4Pj
"""

pip install google-generativeai requests beautifulsoup4

import os
import requests
from bs4 import BeautifulSoup
import google.generativeai as genai
import streamlit as st  # 이 줄이 없으면 맨 위에 추가해주세요!

# 이제 실제 키 대신 '비밀 금고'를 참조합니다
GOOGLE_API_KEY = st.secrets["GEMINI_API_KEY"]
genai.configure(api_key=GOOGLE_API_KEY)

model = genai.GenerativeModel('gemini-2.5-flash')

class HistoryClassifier:
    def __init__(self):
        self.base_url = "https://db.history.go.kr/integrated/search/searchResult.do"
        self.headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
        }

    def scrape_history_db(self, name):
        """
        한국사데이터베이스에서 인물 이름으로 검색하여 관련 텍스트 조각(Snippet)을 수집합니다.
        """
        print(f"🌐 '{name}'에 대한 정보를 한국사데이터베이스에서 수집 중...")

        params = {
            'keyword': name,
            'wc': 'on'  # 전체 검색
        }

        try:
            response = requests.get(self.base_url, params=params, headers=self.headers, timeout=10)
            response.raise_for_status() # 404 등 에러 체크

            soup = BeautifulSoup(response.text, 'html.parser')

            # 검색 결과 리스트 가져오기 (사이트 구조에 따라 클래스명이 다를 수 있음, 일반적인 구조 타겟팅)
            results = soup.select('.ul_list li .cont')

            scraped_texts = []
            if not results:
                # 결과가 없을 경우 다른 선택자 시도
                results = soup.select('.search_result li')

            for item in results[:5]: # 상위 5개 결과만 참조 (토큰 절약 및 속도)
                text = item.get_text(strip=True)
                scraped_texts.append(text)

            if not scraped_texts:
                print("⚠️ 검색 결과가 충분하지 않습니다. AI의 배경지식을 활용합니다.")
                return None

            return "\n".join(scraped_texts)

        except Exception as e:
            print(f"❌ 스크래핑 중 오류 발생: {e}")
            return None

    def analyze_character(self, name):
        """
        수집된 정보와 AI의 지식을 결합하여 인물을 분류합니다.
        """
        # 1. 정보 수집
        db_context = self.scrape_history_db(name)

        # 2. 프롬프트 구성 (RAG 방식)
        prompt = f"""
        당신은 고려 말과 조선 초기의 역사 전문가입니다.
        아래 제공된 '한국사데이터베이스 검색 결과'와 당신의 '배경지식'을 종합하여 다음 작업을 수행하세요.

        분석 대상 인물: {name}

        [한국사데이터베이스 검색 결과]
        {db_context if db_context else "검색 결과 없음 (배경지식 위주로 판단하세요)"}

        [지시사항]
        1. 이 인물이 고려 말 '온건파 사대부(유지파)'인지 '급진파 사대부(역성혁명파)'인지 명확히 분류하세요.
        2. 만약 사대부가 아니거나(무신 등), 분류가 모호하다면 그 사실을 명시하세요.
        3. 분류의 핵심 근거를 3가지 이내로 요약해서 설명하세요.

        [출력 형식]
        - 이름: {name}
        - 분류: [온건파 사대부 / 급진파 사대부 / 기타]
        - 핵심 근거:
          1. ...
          2. ...
        - 한줄 요약: ...
        """

        # 3. AI 분석 실행
        print("🤖 AI가 역사적 사료를 분석 중입니다...")
        try:
            response = model.generate_content(prompt)
            return response.text
        except Exception as e:
            return f"❌ AI 분석 실패: {e}"

# ==========================================
# 메인 실행부
# ==========================================
def main():
    classifier = HistoryClassifier()

    print("=== 고려 말 인물 성향 분류기 (By Gemini & 한국사DB) ===")
    print("종료하려면 'q'를 입력하세요.\n")

    while True:
        user_input = input("인물 이름을 입력하세요 (예: 정몽주, 정도전): ").strip()

        if user_input.lower() == 'q':
            print("프로그램을 종료합니다.")
            break

        if not user_input:
            continue

        result = classifier.analyze_character(user_input)

        print("\n" + "="*40)
        print(result)
        print("="*40 + "\n")

if __name__ == "__main__":
    main()
