# -*- coding: utf-8 -*-
"""노션 웹사이트 웹스크래핑 후 텍스트마이닝.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SPCr2yzQ4wiuk0RSchwb6ePIHQXf0T1R
"""

pip install pandas matplotlib wordcloud scikit-learn nltk konlpy google-generativeai requests

import requests
import pandas as pd
import matplotlib.pyplot as plt
from wordcloud import WordCloud
from konlpy.tag import Okt
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.decomposition import LatentDirichletAllocation
import google.generativeai as genai
from collections import Counter

# 1. 환경 설정
NOTION_TOKEN = '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'
DATABASE_ID = '2d19e99c537880898d81f3b5f9c7b673'
import streamlit as st  # 이 줄이 없으면 맨 위에 추가해주세요!

# 이제 실제 키 대신 '비밀 금고'를 참조합니다
GOOGLE_API_KEY = st.secrets["GEMINI_API_KEY"]
genai.configure(api_key=GOOGLE_API_KEY)

# 1. Google AI Studio 설정
model = genai.GenerativeModel('gemini-2.5-flash')

def get_notion_data(token, db_id):
    url = f"https://api.notion.com/v1/databases/{db_id}/query"
    headers = {
        "Authorization": f"Bearer {token}",
        "Notion-Version": "2022-06-28",
        "Content-Type": "application/json"
    }

    texts = []
    has_more = True
    next_cursor = None

    while has_more:
        payload = {"start_cursor": next_cursor} if next_cursor else {}
        response = requests.post(url, json=payload, headers=headers)

        if response.status_code != 200:
            print(f"❌ API 오류: {response.status_code} - {response.text}")
            break

        data = response.json()

        for row in data.get('results', []):
            properties = row.get('properties', {})
            for prop in properties.values():
                # 모든 텍스트 기반 속성(제목, 리치텍스트, 선택항목 등)에서 텍스트 추출
                if prop['type'] == 'title' and prop['title']:
                    texts.append(prop['title'][0]['plain_text'])
                elif prop['type'] == 'rich_text' and prop['rich_text']:
                    texts.append(prop['rich_text'][0]['plain_text'])
                elif prop['type'] == 'select' and prop['select']:
                    texts.append(prop['select']['name'])
                elif prop['type'] == 'multi_select' and prop['multi_select']:
                    for item in prop['multi_select']:
                        texts.append(item['name'])

        has_more = data.get('has_more', False)
        next_cursor = data.get('next_cursor')

    print(f"✅ 총 {len(texts)}개의 텍스트 조각을 수집했습니다.")
    return texts

def preprocess_korean(texts):
    okt = Okt()
    all_nouns = []
    # 데이터가 없을 경우를 대비한 안전 장치
    if not texts:
        return []
    for text in texts:
        nouns = okt.nouns(text)
        all_nouns.extend([n for n in nouns if len(n) > 1])
    return all_nouns

#노트북이 코랩에서 실행 중인지 체크합니다.

import sys
if 'google.colab' in sys.modules:
  !echo 'debconf debconf/frontend select Noniteractive' | \
  debconf-set-selections

  # 나눔 폰트를 설치합니다.
  !sudo apt-get -qq -y install fonts-nanum
  import matplotlib.font_manager as fm
  font_files = fm.findSystemFonts(fontpaths=['/usr/share/fonts/truetype/nanum'])
  for fpath in font_files:
    fm.fontManager.addfont(fpath)

import matplotlib.pyplot as plt
plt.rc('font', family='NanumBarunGothic')
plt.rcParams['figure.dpi']=100

import platform
import matplotlib.pyplot as plt
import pandas as pd
from wordcloud import WordCloud
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.decomposition import LatentDirichletAllocation

# 1. 폰트 강제 설정 함수
def get_reliable_font():
    sys_name = platform.system()
    if sys_name == "Windows":
        return "malgun.ttf"
    elif sys_name == "Darwin":
        return "/System/Library/Fonts/Supplemental/AppleGothic.ttf"
    else:
        # Colab/Linux 환경에서 폰트가 없을 경우를 대비해 나눔폰트 설치 확인
        import os
        colab_font = '/usr/share/fonts/truetype/nanum/NanumGothic.ttf'
        if os.path.exists(colab_font):
            return colab_font
        else:
            print("💡 Colab 환경: 폰트가 없습니다. 설치 후 실행을 권장합니다.")
            return None

# 2. 통합 분석 실행 (이 부분으로 기존 실행부를 대체하세요)
try:
    print("🚀 데이터 분석을 시작합니다...")
    raw_texts = get_notion_data(NOTION_TOKEN, DATABASE_ID)

    if not raw_texts:
        print("⚠️ 데이터가 없습니다. 노션 설정을 확인하세요.")
    else:
        nouns = preprocess_korean(raw_texts)
        count = dict(Counter(nouns).most_common(100)) # 빈도수 상위 100개

        # --- A. 워드클라우드 강제 출력 ---
        print("🎨 워드클라우드 시각화 중...")
        font = get_reliable_font()

        # 폰트가 없더라도 기본 폰트로 실행되도록 예외 처리 강화
        wc = WordCloud(
            font_path=font,
            background_color='white',
            width=1000,
            height=600,
            prefer_horizontal=0.9,
            colormap='coolwarm'
        ).generate_from_frequencies(count)

        plt.figure(figsize=(12, 7))
        plt.imshow(wc, interpolation='bilinear')
        plt.axis('off')
        plt.title("< Notion Content Analysis >", fontsize=20)
        plt.show()

        # --- B. 토픽 모델링 결과 시각화 ---
        print("🧬 토픽 모델링 분석 및 결과 출력...")
        n_topics = 3
        vectorizer = CountVectorizer(max_features=1000)
        data_vectorized = vectorizer.fit_transform(raw_texts)

        lda = LatentDirichletAllocation(n_components=n_topics, random_state=42)
        lda.fit(data_vectorized)

        # 토픽별 주요 단어 추출 및 표 작성
        feature_names = vectorizer.get_feature_names_out()
        topics_data = []

        for idx, topic in enumerate(lda.components_):
            top_words = [feature_names[i] for i in topic.argsort()[:-11:-1]]
            topics_data.append({"Topic": f"주제 {idx+1}", "Keywords": ", ".join(top_words)})

        df_topics = pd.DataFrame(topics_data)
        print("\n[토픽 모델링 결과 요약]")
        print(df_topics) # 콘솔 출력

        # 주피터/Colab 환경에서 표로 예쁘게 출력
        from IPython.display import display
        display(df_topics)

        # --- C. Gemini AI 심층 요약 ---
        print("\n🤖 AI 심층 분석 리포트 생성 중...")
        full_content = " ".join(raw_texts)[:3000]
        prompt = f"다음은 수집된 교육/기술 데이터입니다. 1.핵심 주제 3가지 2.키워드 연관성 3.미래 전망을 요약해줘: {full_content}"
        response = model.generate_content(prompt)
        print("\n" + "="*50 + "\n" + response.text + "\n" + "="*50)

except Exception as e:
    print(f"❗ 분석 중 오류 발생: {e}")
