# -*- coding: utf-8 -*-
"""병자호란 당시 주전론과 주화론 분류(개발중).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nhF71TrL2bjESiCJIS_kWDVuSEznn7sn
"""

pip install google-generativeai requests beautifulsoup4

import google.generativeai as genai
import requests
from bs4 import BeautifulSoup
import streamlit as st  # 이 줄이 없으면 맨 위에 추가해주세요!

# 이제 실제 키 대신 '비밀 금고'를 참조합니다
GOOGLE_API_KEY = st.secrets["GEMINI_API_KEY"]
genai.configure(api_key=GOOGLE_API_KEY)


# 경고 메시지가 불편하다면 최신 패키지(google.genai)로 마이그레이션이 필요하지만,
# 현재 코드 작동을 위해 기존 방식을 유지하되 오류를 방지합니다.
try:
    genai.configure(api_key=API_KEY)
    model = genai.GenerativeModel('gemini-flash-2.5')
except Exception as e:
    print(f"⚠️ Gemini 설정 오류: {e}")

# ==========================================
# 2. 웹 스크래핑 함수 (수정됨: 헤더 추가 및 HTTPS 적용)
# ==========================================
def scrape_historical_records(person_name):
    """
    조선왕조실록 사이트에서 인물 이름으로 검색하여
    봇 차단을 우회하고 데이터를 가져옵니다.
    """
    print(f"🔍 '{person_name}'에 대한 기록을 한국사데이터베이스에서 검색 중...")

    # [수정 1] http -> https (보안 연결 사용)
    base_url = "https://sillok.history.go.kr/search/searchResultList.do"

    # [수정 2] 봇 차단 방지를 위한 'User-Agent' 헤더 추가 (브라우저인 척하기)
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
    }

    # [수정 3] 검색 파라미터 점검
    params = {
        'searchKeyword': person_name, # 사이트 구조에 맞춰 파라미터명 변경 가능성 대비
        'rowPerPage': 5               # 빠른 응답을 위해 5건으로 조정
    }

    try:
        # timeout 설정으로 무한 로딩 방지
        response = requests.get(base_url, headers=headers, params=params, timeout=10)

        # 400/500 에러 발생 시 예외 처리
        response.raise_for_status()

        soup = BeautifulSoup(response.text, 'html.parser')

        results = []
        # 사이트 구조에 따른 선택자 (실제 사이트 HTML 구조에 의존함)
        articles = soup.select("ul.result_list > li")

        if not articles:
            # 검색 결과가 없을 경우 예외 처리
            print(f"   👉 '{person_name}'에 대한 검색 결과가 없습니다.")
            return None

        for i, article in enumerate(articles):
            if i >= 3: break # 너무 많은 데이터는 토큰 낭비이므로 상위 3개만 사용

            title_tag = article.select_one("dl > dt > a")
            if title_tag:
                title = title_tag.get_text(strip=True)
                desc_tag = article.select_one("dl > dd.desc")
                desc = desc_tag.get_text(strip=True) if desc_tag else ""
                results.append(f"기사: {title}\n내용: {desc}")

        full_text = "\n---\n".join(results)
        return full_text

    except requests.exceptions.HTTPError as e:
        print(f"❌ 서버 연결 거부 (HTTP Error): {e}")
        return None
    except Exception as e:
        print(f"❌ 스크래핑 중 알 수 없는 오류: {e}")
        return None

# ==========================================
# 3. AI 분석 및 분류 함수
# ==========================================
def classify_figure(person_name, historical_text):
    if not historical_text:
        return "데이터 부족으로 분석할 수 없습니다."

    print(f"🤖 Gemini가 '{person_name}'의 성향을 분석 중입니다...\n")

    prompt = f"""
    당신은 한국사 전문가입니다.
    아래는 조선왕조실록에서 '{person_name}'을 검색한 결과입니다.
    이 내용을 바탕으로 이 인물이 '병자호란(1636)' 당시 어떤 입장이었는지 판별하세요.

    [분석 텍스트]
    {historical_text}

    [필수 답변 양식]
    1. 분류: [주전론자 (척화파) / 주화론자 (주화파) / 판단 불가]
    2. 이유: (학생들이 이해하기 쉽게 2문장 내외로 설명)
    """

    try:
        response = model.generate_content(prompt)
        return response.text
    except Exception as e:
        return f"❌ API 분석 오류: {e}"

# ==========================================
# 4. 실행부
# ==========================================
if __name__ == "__main__":
    while True:
        target_name = input("\n인물 이름을 입력하세요 (종료: q): ").strip()
        if target_name.lower() == 'q': break
        if not target_name: continue

        data = scrape_historical_records(target_name)

        if data:
            analysis = classify_figure(target_name, data)
            print("\n--- 분석 결과 ---")
            print(analysis)
        else:
            print(f"'{target_name}'에 대한 기록을 찾을 수 없어서 분석을 진행할 수 없습니다.")

import google.generativeai as genai
import requests
from bs4 import BeautifulSoup

# ==========================================
# 1. API 키 설정
# ==========================================
API_KEY = "AIzaSyBEmAHr7r1i2mt8yu6qjp3P79ErIfQrIfw"  # API 키를 다시 입력해주세요.

try:
    genai.configure(api_key=API_KEY)
    model = genai.GenerativeModel('gemini-pro')
except Exception as e:
    print(f"⚠️ Gemini 설정 오류: {e}")

# ==========================================
# 2. 웹 스크래핑 함수 (최종 수정버전)
# ==========================================
def scrape_historical_records(person_name):
    print(f"🔍 '{person_name}' 검색 중... (한국사데이터베이스)")

    # 1. URL: HTTP 사용 (HTTPS 강제 시 오류 가능성 배제)
    base_url = "http://sillok.history.go.kr/search/searchResultList.do"

    # 2. 헤더: 브라우저인 척 위장 (400 에러 방지 핵심)
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36',
        'Referer': 'http://sillok.history.go.kr/'
    }

    # 3. 파라미터: 'keyword'가 정확한 변수명입니다 (404 에러 방지 핵심)
    params = {
        'keyword': person_name,
        'rowPerPage': 5
    }

    try:
        response = requests.get(base_url, headers=headers, params=params, timeout=10)
        response.raise_for_status() # 400, 404, 500 등 에러 발생 시 즉시 알림

        soup = BeautifulSoup(response.text, 'html.parser')

        results = []
        articles = soup.select("ul.result_list > li")

        if not articles:
            print(f"   👉 '{person_name}' 검색 결과가 없습니다.")
            return None

        # 상위 3개 기사만 요약해서 가져오기
        for i, article in enumerate(articles):
            if i >= 3: break

            title_tag = article.select_one("dl > dt > a")
            if title_tag:
                title = title_tag.get_text(strip=True)
                desc_tag = article.select_one("dl > dd.desc")
                desc = desc_tag.get_text(strip=True) if desc_tag else ""
                results.append(f"- 기사: {title}\n- 내용: {desc}")

        return "\n\n".join(results)

    except Exception as e:
        print(f"❌ 스크래핑 오류: {e}")
        return None

# ==========================================
# 3. AI 분석 함수
# ==========================================
def classify_figure(person_name, historical_text):
    # 스크래핑 데이터가 없으면 Gemini 내장 지식으로 대체 (수업 끊김 방지)
    if not historical_text:
        print("⚠️ 웹 검색 실패. Gemini의 내장 지식을 사용합니다.")
        prompt = f"""
        조선시대 인물 '{person_name}'이 병자호란(1636) 당시
        청나라와 싸우자는 '주전론(척화파)'이었는지, 화친하자는 '주화론(주화파)'이었는지 판별해줘.

        답변 형식:
        1. 분류: [주전론자 / 주화론자]
        2. 이유: 한 문장으로 요약
        """
    else:
        prompt = f"""
        다음은 조선왕조실록 검색 결과입니다.
        이를 바탕으로 '{person_name}'이 병자호란 당시 어떤 입장이었는지 판별하시오.

        [검색 결과]
        {historical_text}

        답변 형식:
        1. 분류: [주전론자 / 주화론자]
        2. 이유: 검색된 내용을 바탕으로 설명
        """

    try:
        response = model.generate_content(prompt)
        return response.text
    except Exception as e:
        return f"❌ 분석 오류: {e}"

# ==========================================
# 4. 실행
# ==========================================
if __name__ == "__main__":
    while True:
        name = input("\n인물 이름 입력 (종료: q): ").strip()
        if name.lower() == 'q': break
        if not name: continue

        # 스크래핑 시도
        data = scrape_historical_records(name)

        # 결과 출력
        print("-" * 30)
        print(classify_figure(name, data))
        print("-" * 30)
