# -*- coding: utf-8 -*-
"""병자호란당시 주전론자와 주화론자 분류모델.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15YQC_WP-r5f5NAQqScM5hlEOgJ90gO7k
"""

import requests
from bs4 import BeautifulSoup
import google.generativeai as genai
import textwrap
import streamlit as st  # 이 줄이 없으면 맨 위에 추가해주세요!

# 이제 실제 키 대신 '비밀 금고'를 참조합니다
GOOGLE_API_KEY = st.secrets["GEMINI_API_KEY"]
genai.configure(api_key=GOOGLE_API_KEY)

model = genai.GenerativeModel('gemini-1.5-flash') # 속도와 효율성을 위해 Flash 모델 사용

# ==========================================
# 2. 웹 스크래핑 함수 (Web Scraper)
# ==========================================
def scrape_history_net(person_name):
    """
    우리역사넷(contents.history.go.kr)에서 인물 정보를 검색하여 텍스트를 추출합니다.
    """
    base_url = "https://contents.history.go.kr/front/search/totalSearch.do"

    # 검색 파라미터 설정
    params = {
        'searchText': person_name,
        'searchType': 'all'
    }

    # 봇 차단 방지를 위한 헤더 설정
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
    }

    try:
        print(f"🌐 '{person_name}'에 대한 정보를 우리역사넷에서 수집 중...")
        response = requests.get(base_url, params=params, headers=headers)
        response.raise_for_status() # 에러 체크

        soup = BeautifulSoup(response.text, 'html.parser')

        # 검색 결과에서 텍스트 추출 (사이트 구조에 따라 class명은 변동될 수 있음)
        # 일반적인 검색 결과 리스트의 요약 내용을 가져옵니다.
        results = []

        # 'search_list' 클래스 내의 텍스트들을 수집 (예시 구조)
        search_items = soup.select('.search_list li .conts')

        for item in search_items[:3]: # 상위 3개 결과만 참조
            text = item.get_text(strip=True)
            results.append(text)

        if not results:
            print("   ⚠️ 검색 결과에서 상세 텍스트를 찾을 수 없습니다. (LLM 지식에 의존합니다)")
            return None

        combined_text = "\n".join(results)
        print(f"   ✅ 데이터 수집 완료 ({len(combined_text)}자)")
        return combined_text

    except Exception as e:
        print(f"   ❌ 스크래핑 중 오류 발생: {e}")
        return None

# ==========================================
# 3. AI 분류 모델 함수 (AI Classifier)
# ==========================================
def classify_political_stance(name, context_text):
    """
    수집된 정보를 바탕으로 Gemini가 주전론/주화론을 분류합니다.
    """

    # 컨텍스트가 없으면(스크래핑 실패 시) LLM의 기본 지식을 사용하도록 프롬프트 조정
    context_prompt = ""
    if context_text:
        context_prompt = f"참고할 역사적 사료 내용:\n{context_text}\n\n"

    prompt = f"""
    당신은 한국사 전문가입니다.
    아래 [입력된 인물]이 병자호란(1636년) 당시 어떤 정치적 입장을 취했는지 분석해주세요.

    [입력된 인물]: {name}
    {context_prompt}

    다음 지침에 따라 답변해주세요:
    1. 결론: 이 사람이 '주전론자(척화파)'인지 '주화론자(주화파)'인지, 혹은 '중립/기타'인지 명확히 분류하세요.
    2. 근거: 위 분류의 이유를 역사적 사실에 기반하여 2~3문장으로 요약하세요.
    3. 만약 병자호란과 관련이 없는 인물이라면 "병자호란과 직접적인 관련이 없거나 정보가 부족합니다"라고 답변하세요.
    """

    try:
        response = model.generate_content(prompt)
        return response.text
    except Exception as e:
        return f"API 호출 중 오류 발생: {e}"

# ==========================================
# 4. 메인 실행 함수 (Main)
# ==========================================
def main():
    print("=== 병자호란 인물 성향 분류기 (우리역사넷 + Google Gemini) ===")
    print("예시: 김상헌, 최명길, 홍익한, 인조 등")

    while True:
        target_person = input("\n🔎 인물 이름을 입력하세요 (종료하려면 'q' 입력): ").strip()

        if target_person.lower() == 'q':
            print("프로그램을 종료합니다.")
            break

        if not target_person:
            continue

        # 1단계: 웹 스크래핑
        scraped_data = scrape_history_net(target_person)

        # 2단계: AI 분류
        print("🤖 AI가 역사를 분석하고 있습니다...")
        result = classify_political_stance(target_person, scraped_data)

        # 결과 출력
        print("\n" + "="*40)
        print(f"[{target_person}] 분류 결과")
        print("="*40)
        print(result)
        print("="*40)

if __name__ == "__main__":
    main()

pip install --upgrade google-generativeai requests beautifulsoup4

import requests
from bs4 import BeautifulSoup
import google.generativeai as genai
import urllib3

# SSL 경고 메시지 숨기기 (깔끔한 출력을 위해)
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

# ==========================================
# 1. 설정 (Configuration)
# ==========================================

# 이제 실제 키 대신 '비밀 금고'를 참조합니다
GOOGLE_API_KEY = st.secrets["GEMINI_API_KEY"]
genai.configure(api_key=GOOGLE_API_KEY)

# Gemini 모델 설정
try:
    genai.configure(api_key=GOOGLE_API_KEY)
    # 최신 라이브러리에서는 flash 모델 사용 가능. 만약 404 에러가 계속되면 'gemini-pro'로 변경하세요.
    model = genai.GenerativeModel('gemini-2.5-flash')
except Exception as e:
    print(f"모델 설정 중 오류 발생: {e}")

# ==========================================
# 2. 웹 스크래핑 함수 (Web Scraper) - 수정됨
# ==========================================
def scrape_history_net(person_name):
    """
    우리역사넷에서 인물 정보를 검색합니다. (SSL 검증 무시 및 헤더 강화)
    """
    base_url = "https://contents.history.go.kr/front/search/totalSearch.do"

    params = {
        'searchText': person_name,
        'searchType': 'all'
    }

    # 헤더를 더 상세하게 설정하여 차단 우회 시도
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
        'Referer': 'https://contents.history.go.kr/',
        'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8'
    }

    try:
        print(f"🌐 '{person_name}'에 대한 정보를 우리역사넷에서 찾는 중...")

        # verify=False 옵션 추가 (SSL 인증서 오류 무시)
        response = requests.get(base_url, params=params, headers=headers, verify=False, timeout=10)

        if response.status_code != 200:
            print(f"   ⚠️ 사이트 접속 실패 (상태 코드: {response.status_code}) -> AI 지식만 사용합니다.")
            return None

        soup = BeautifulSoup(response.text, 'html.parser')

        # 검색 결과 텍스트 추출
        results = []
        search_items = soup.select('.search_list li .conts')

        for item in search_items[:3]:
            text = item.get_text(strip=True)
            results.append(text)

        if not results:
            print("   ⚠️ 검색 결과 텍스트를 찾을 수 없음 -> AI 지식만 사용합니다.")
            return None

        combined_text = "\n".join(results)
        print(f"   ✅ 데이터 수집 성공 ({len(combined_text)}자)")
        return combined_text

    except Exception as e:
        # 오류가 나도 멈추지 않고 None을 반환하여 AI가 처리하게 함
        print(f"   ⚠️ 스크래핑 건너뜀 (사유: {e}) -> AI 지식만 사용합니다.")
        return None

# ==========================================
# 3. AI 분류 모델 함수
# ==========================================
def classify_political_stance(name, context_text):

    context_prompt = ""
    if context_text:
        context_prompt = f"참고할 우리역사넷 검색 결과:\n{context_text}\n\n"

    prompt = f"""
    당신은 한국사 전문가입니다.
    아래 [입력된 인물]이 병자호란(1636년) 당시 어떤 정치적 입장을 취했는지 분석해주세요.

    [입력된 인물]: {name}
    {context_prompt}

    다음 형식으로 답변해주세요:
    1. **분류**: [주전론(척화파) / 주화론(주화파) / 중립 / 관련 없음] 중 택 1
    2. **핵심 이유**: 역사적 사실에 기반하여 2문장 내외로 요약
    """

    try:
        response = model.generate_content(prompt)
        return response.text
    except Exception as e:
        return f"❌ AI 분석 중 오류 발생: {e}\n(팁: google-generativeai 라이브러리를 업데이트해보세요)"

# ==========================================
# 4. 메인 실행 함수
# ==========================================
def main():
    print("=== 병자호란 인물 성향 분류기 (수정버전) ===")

    while True:
        target_person = input("\n🔎 인물 이름 입력 (종료: q): ").strip()

        if target_person.lower() == 'q':
            print("종료합니다.")
            break

        if not target_person:
            continue

        # 1단계: 스크래핑 (실패해도 프로그램 죽지 않음)
        scraped_data = scrape_history_net(target_person)

        # 2단계: AI 분류
        print("🤖 AI 분석 중...")
        result = classify_political_stance(target_person, scraped_data)

        print("-" * 50)
        print(result)
        print("-" * 50)

if __name__ == "__main__":
    main()
