# -*- coding: utf-8 -*-
"""세계사 인물 검색기(위키백과 웹스크래핑).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IbzB_GgzIfsPUZH0R-mlNxMoY9lfGsX_
"""

pip install google-generativeai requests beautifulsoup4

import requests
from bs4 import BeautifulSoup
import google.generativeai as genai
import urllib.parse  # 한글 URL 처리를 위한 모듈 추가

def get_wiki_text(name):
    """
    위키백과에서 해당 인물의 페이지 텍스트를 가져옵니다.
    """
    base_url = "https://ko.wikipedia.org/wiki/"

    # [수정 1] 한글 이름을 URL 전용 문자열로 변환 (예: 나폴레옹 -> %EB%82%98...)
    encoded_name = urllib.parse.quote(name)
    url = base_url + encoded_name

    # [수정 2] 위키백과가 봇을 차단하지 않도록 'User-Agent' 헤더 추가
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
    }

    try:
        # headers 정보를 함께 전송
        response = requests.get(url, headers=headers)

        # 페이지가 없거나 오류가 나면 None 반환
        if response.status_code != 200:
            print(f"⚠️ 접속 오류 코드: {response.status_code}") # 디버깅용 출력
            return None

        soup = BeautifulSoup(response.text, 'html.parser')

        # 본문 내용이 있는 div만 선택
        content_div = soup.find('div', {'class': 'mw-parser-output'})

        if content_div:
            text = content_div.get_text()
            return text[:5000]
        return None

    except Exception as e:
        print(f"웹 스크래핑 중 오류 발생: {e}")
        return None

def analyze_with_gemini(api_key, name, wiki_text):
    """
    Gemini API를 호출하여 텍스트에서 정보를 추출합니다.
    """
    # API 키 설정
    genai.configure(api_key=api_key)

    # 모델 설정
    model = genai.GenerativeModel('gemini-2.5-flash')

    # 프롬프트 작성
    prompt = f"""
    당신은 역사 교육 전문가입니다. 아래 제공된 위키백과 텍스트를 읽고
    '{name}'라는 인물에 대한 정보를 다음 형식으로 정리해 주세요.

    [출력 형식]
    국적: (국적 정보, 확실하지 않으면 '정보 없음'으로 표기)
    주요 활동: (이 인물이 역사적으로 어떤 일을 했는지 중학생이 이해하기 쉽게 3문장 내외로 요약)

    [위키백과 텍스트]
    {wiki_text}
    """

    try:
        response = model.generate_content(prompt)
        return response.text
    except Exception as e:
        return f"AI 분석 중 오류 발생: {e}"

# --- 메인 실행 부분 ---
if __name__ == "__main__":
    print("=== AI 기반 위키백과 인물 분석기 (Gemini API) ===")

    user_api_key = input("Google AI Studio API Key를 입력하세요: ").strip()

    if not user_api_key:
        print("API Key가 입력되지 않았습니다. 프로그램을 종료합니다.")
        exit()

    print("\n✅ 설정 완료! 인물 검색을 시작합니다. (종료: q)")

    while True:
        target_name = input("\n인물 이름을 입력하세요 (예: 이순신, 나폴레옹): ").strip()

        if target_name.lower() == 'q':
            print("프로그램을 종료합니다.")
            break

        if not target_name:
            continue

        print(f"🔍 '{target_name}' 위키백과 데이터 수집 중...")

        # 스크래핑 시도
        raw_text = get_wiki_text(target_name)

        if raw_text is None:
            print(f"❌ '{target_name}' 문서를 찾을 수 없습니다.")
            print("   (팁: 정확한 띄어쓰기나 공식 표제어를 입력해보세요. 예: '나폴레옹 보나파르트')")
        else:
            print(f"🤖 Gemini가 '{target_name}'에 대해 분석 중입니다...")
            result = analyze_with_gemini(user_api_key, target_name, raw_text)

            print("-" * 50)
            print(f"📌 인물: {target_name}")
            print(result.strip())
            print("-" * 50)

import google.generativeai as genai
import streamlit as st  # 이 줄이 없으면 맨 위에 추가해주세요!

# 이제 실제 키 대신 '비밀 금고'를 참조합니다
GOOGLE_API_KEY = st.secrets["GEMINI_API_KEY"]
genai.configure(api_key=GOOGLE_API_KEY)


print("=== 사용 가능한 모델 목록 ===")
for m in genai.list_models():
    # 'generateContent' 기능(채팅/텍스트 생성)이 있는 모델만 출력
    if 'generateContent' in m.supported_generation_methods:
        print(m.name)
