# -*- coding: utf-8 -*-
"""일제강점기 한국사인물 성향 분류기(한국민족문화대백과 웹스크래핑).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11J9Eeuzwu6Cmqb6f_z19cFjmo7pwW8y4
"""

# [1] 라이브러리 강제 업데이트 (이 코드를 가장 먼저 실행해야 404 오류가 사라집니다)
!pip install -U google-generativeai requests beautifulsoup4

import google.generativeai as genai
import requests
from bs4 import BeautifulSoup
import random
import json
import time
import os
import streamlit as st  # 이 줄이 없으면 맨 위에 추가해주세요!

# 이제 실제 키 대신 '비밀 금고'를 참조합니다
GOOGLE_API_KEY = st.secrets["GEMINI_API_KEY"]
genai.configure(api_key=GOOGLE_API_KEY)


# 모델 설정 (혹시 flash 모델이 안 되면 pro 모델로 자동 전환하도록 예외처리 추가함)
def get_model():
    try:
        model = genai.GenerativeModel('gemini-2.5-flash')
        return model
    except:
        print("⚠️ Flash 모델 로딩 실패, 기본 Pro 모델로 전환합니다.")
        return genai.GenerativeModel('gemini-pro')

model = get_model()

# =========================================================
# 3. 웹 스크래핑 함수
# =========================================================
def scrap_history_data(name):
    print(f"🔍 '{name}'에 대한 자료를 한국민족문화대백과에서 찾는 중...")
    url = f"https://encykorea.aks.ac.kr/Article/Search/{name}"

    try:
        headers = {'User-Agent': 'Mozilla/5.0'}
        response = requests.get(url, headers=headers)
        if response.status_code != 200: return None
        soup = BeautifulSoup(response.text, 'html.parser')
        text_content = soup.get_text()
        return text_content[:5000] # 너무 길면 자름
    except Exception as e:
        print(f"❌ 스크래핑 오류: {e}")
        return None

# =========================================================
# 4. AI 분류 함수
# =========================================================
def classify_figure_with_ai(name, context_text):
    print(f"🤖 AI가 '{name}'의 성향을 분석 중입니다...")

    prompt = f"""
    당신은 한국사 전문가입니다. 아래 [텍스트]는 '{name}'에 대한 자료입니다.
    이 내용을 바탕으로 이 인물의 성향을 다음 중 하나로 분류하고 이유를 설명해주세요.

    [분류 기준]
    1. 무장투쟁론 (무력 독립 운동)
    2. 실력양성론 (교육/산업 육성)
    3. 외교론 (국제 사회 호소)
    4. 친일파 (반민족 행위)
    5. 기타 (해당 없음)

    [출력 형식 - JSON]
    {{
        "name": "{name}",
        "classification": "분류 결과",
        "reason": "판단 이유 한 줄 요약"
    }}

    [텍스트]
    {context_text}
    """

    try:
        response = model.generate_content(prompt)
        # JSON 형식 정제
        text = response.text.replace("```json", "").replace("```", "").strip()
        return json.loads(text)
    except Exception as e:
        print(f"❌ AI 응답 오류: {e}")
        return None

# =========================================================
# 5. 메인 실행 (입력 로직 수정됨)
# =========================================================
def main():
    history_figures = ["김구", "안창호", "이승만", "이완용", "김원봉", "신채호", "윤봉길"]

    print("\n" + "="*50)
    print("   🚀 AI 한국사 인물 성향 분류기 (수정버전)")
    print("="*50)

    while True:
        # 선생님의 의도대로 입력을 받도록 수정했습니다.
        user_input = input("\n👉 인물 이름을 입력하세요 (그냥 엔터치면 랜덤, 'q'는 종료): ").strip()

        if user_input.lower() == 'q':
            print("프로그램을 종료합니다.")
            break

        # 입력값이 있으면 그 사람을, 없으면 랜덤으로 선택
        if user_input:
            target_person = user_input
        else:
            target_person = random.choice(history_figures)

        print(f"\n🎯 분석 대상: [{target_person}]")

        # 자료 수집
        scraped_text = scrap_history_data(target_person)

        if not scraped_text or len(scraped_text) < 50:
            print("⚠ 자료를 찾지 못했습니다. 올바른 인물명인지 확인해주세요.")
            continue

        # AI 분석
        result = classify_figure_with_ai(target_person, scraped_text)

        if result:
            print("-" * 40)
            print(f" 🏷️  이름: {result.get('name')}")
            print(f" 🚩 성향: {result.get('classification')}")
            print(f" 💡 이유: {result.get('reason')}")
            print("-" * 40)

        time.sleep(1)

if __name__ == "__main__":
    main()
